<?php
/*
* Generated By Orbisius Child Theme Creator - your favorite plugin for Child Theme creation :)
* https://wordpress.org/plugins/orbisius-child-theme-creator/
*
* Unlike style.css, the functions.php of a child theme does not override its counterpart from the parent.
* Instead, it is loaded in addition to the parent’s functions.php. (Specifically, it is loaded right before the parent theme's functions.php).
* Source: http://codex.wordpress.org/Child_Themes#Using_functions.php
*
* Be sure not to define functions, that already exist in the parent theme!
* A common pattern is to prefix function names with the (child) theme name.
* Also if the parent theme supports pluggable functions you can use function_exists( 'put_the_function_name_here' ) checks.
*/

/**
 * Loads parent and child themes' style.css
 */
function orbisius_ct_generatepress_child_child_theme_enqueue_styles() {
    $parent_style = 'orbisius_ct_generatepress_child_parent_style';
    $parent_base_dir = 'generatepress';

    //boostrap style
    wp_enqueue_style( 'bootstrap_css', 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css' );

    wp_enqueue_style( $parent_style,
        get_template_directory_uri() . '/style.css',
        array(),
        wp_get_theme( $parent_base_dir ) ? wp_get_theme( $parent_base_dir )->get('Version') : ''
    );

    wp_enqueue_style( $parent_style . '_child_style',
        get_stylesheet_directory_uri() . '/style.css',
        array( $parent_style ),
        wp_get_theme()->get('Version')
    );

    //enqueue bootstrap scripts
    global $wp_scripts;

	wp_enqueue_script( 'bootstrap_js', 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js');
	wp_enqueue_script( 'vu_custom_js', get_template_directory_uri() . '/js/scripts.js');
}

add_action( 'wp_enqueue_scripts', 'orbisius_ct_generatepress_child_child_theme_enqueue_styles' );

add_filter( 'generate_copyright','vu_custom_copyright' );
function vu_custom_copyright() {
    ?>
    <address>
        <strong>© Valparaiso University 2018</strong>, 
        Valparaiso, 
        IN 46383-6493, 
        219.464.5000
        | <a href="http://valpo.edu/copyright/">Privacy Policy</a> 
        | <a href="http://www.valpo.edu/about/contact-us/website-feedback/">
            <i class="fa fa-comments-o" aria-hidden="true"></i> Website Feedback</a>
    </address>
    <?php
}

// font awesome provided by https://github.com/MickeyKay/better-font-awesome-library

 /**
  * Initialize the Better Font Awesome Library.
  *
  * (see usage notes below on proper hook priority)
  */
add_action( 'init', 'vu_load_bfa' );
 function vu_load_bfa() {

 	// Include the main library file. Make sure to modify the path to match your directory structure.
 	require_once ( dirname( __FILE__ ) . '/better-font-awesome-library/better-font-awesome-library.php' );

 	// Set the library initialization args (defaults shown).
 	$args = array(
 			'version'             => 'latest',
 			'minified'            => true,
 			'remove_existing_fa'  => false,
 			'load_styles'         => true,
 			'load_admin_styles'   => true,
 			'load_shortcode'      => true,
 			'load_tinymce_plugin' => true,
 	);

 	// Initialize the Better Font Awesome Library.
 	Better_Font_Awesome_Library::get_instance( $args );
 }


// /**
//  * Enqueue Font Awesome.
//  */
// add_action( 'wp_enqueue_scripts', 'vu_load_font_awesome' );
// function vu_load_font_awesome() {
//     wp_enqueue_script( 'font-awesome', '//use.fontawesome.com/releases/v5.0.13/js/all.js', array(), null );
// }

// /**
//  * Defer Font Awesome.
//  */
// add_filter( 'script_loader_tag', 'vu_defer_font_awesome', 10, 2 );
// function vu_defer_font_awesome( $tag, $handle ) {
//     if ( 'font-awesome' === $handle ) {
//         $tag = str_replace( ' src', ' defer src', $tag );
//     }
//     return $tag;
// }